version: "3.7"

services:
    server:
        image: ubuntu:20.04
        stdin_open: true
        tty: true
        volumes:
            - ./server-volume:/ext-files/
    client:
        image: ubuntu:20.04
        stdin_open: true
        tty: true
        volumes:
            - ./client-volume:/ext-files/